In [1]:
#1. Import the NUMPY package under the name np.

In [2]:
import numpy as np

In [3]:
#2. Print the NUMPY version and the configuration.

In [4]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Itzel/Documents/Software/Anaconda/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Itzel/Documents/Software/Anaconda/Anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Itzel/Documents/Software/Anaconda/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Pro

In [5]:
np.__config__

<module 'numpy.__config__' from 'C:\\Users\\Itzel\\Documents\\Software\\Anaconda\\Anaconda\\lib\\site-packages\\numpy\\__config__.py'>

In [6]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [7]:
a =  np.random.random((2,3,5))


In [8]:
#4. Print a.
a

array([[[0.84932765, 0.37982056, 0.2816592 , 0.85704966, 0.76864715],
        [0.08277764, 0.63036587, 0.74416352, 0.28660003, 0.58585179],
        [0.07391217, 0.01470447, 0.82287469, 0.20937815, 0.51117295]],

       [[0.97244126, 0.54927618, 0.19375934, 0.50618892, 0.62288682],
        [0.95800711, 0.47398626, 0.28026456, 0.63822721, 0.82986077],
        [0.12157753, 0.34594412, 0.57602973, 0.48517866, 0.63092448]]])

In [9]:
#5. Create a 5x3x2 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

In [10]:
b = np.ones( (5,3,2), dtype=np.int16 )

In [11]:
#6. Print b.

In [12]:
b

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int16)

In [13]:
#7. Do a and b have the same size? How do you prove that in Python code?

In [14]:
print('size a :', a.size)
print('size b :', b.size)

size a : 30
size b : 30


In [15]:
#8. Are you able to add a and b? Why or why not?

In [16]:
# No se pueden sumar ya que sus dimensiones son distintias

In [17]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). 
# Assign the transposed array to varialbe "c".

In [18]:
c = b.T

In [19]:
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)

In [20]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [21]:
d = a+c

In [22]:
# Porque tanto a como c tienen dimensiones 2x3x5

In [23]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [24]:
print(a)

[[[0.84932765 0.37982056 0.2816592  0.85704966 0.76864715]
  [0.08277764 0.63036587 0.74416352 0.28660003 0.58585179]
  [0.07391217 0.01470447 0.82287469 0.20937815 0.51117295]]

 [[0.97244126 0.54927618 0.19375934 0.50618892 0.62288682]
  [0.95800711 0.47398626 0.28026456 0.63822721 0.82986077]
  [0.12157753 0.34594412 0.57602973 0.48517866 0.63092448]]]


In [25]:
print(d)

[[[1.84932765 1.37982056 1.2816592  1.85704966 1.76864715]
  [1.08277764 1.63036587 1.74416352 1.28660003 1.58585179]
  [1.07391217 1.01470447 1.82287469 1.20937815 1.51117295]]

 [[1.97244126 1.54927618 1.19375934 1.50618892 1.62288682]
  [1.95800711 1.47398626 1.28026456 1.63822721 1.82986077]
  [1.12157753 1.34594412 1.57602973 1.48517866 1.63092448]]]


In [26]:
# La suma de a y c, se realiza entrada por entrada, por lo tanto cada entrada de d será igual a la entrada de a + 1

In [27]:
#12. Multiply a and c. Assign the result to e.

In [28]:
e = a*c

In [29]:
#13. Does e equal to a? Why or why not?

In [30]:
print(a)

[[[0.84932765 0.37982056 0.2816592  0.85704966 0.76864715]
  [0.08277764 0.63036587 0.74416352 0.28660003 0.58585179]
  [0.07391217 0.01470447 0.82287469 0.20937815 0.51117295]]

 [[0.97244126 0.54927618 0.19375934 0.50618892 0.62288682]
  [0.95800711 0.47398626 0.28026456 0.63822721 0.82986077]
  [0.12157753 0.34594412 0.57602973 0.48517866 0.63092448]]]


In [31]:
print(e)

[[[0.84932765 0.37982056 0.2816592  0.85704966 0.76864715]
  [0.08277764 0.63036587 0.74416352 0.28660003 0.58585179]
  [0.07391217 0.01470447 0.82287469 0.20937815 0.51117295]]

 [[0.97244126 0.54927618 0.19375934 0.50618892 0.62288682]
  [0.95800711 0.47398626 0.28026456 0.63822721 0.82986077]
  [0.12157753 0.34594412 0.57602973 0.48517866 0.63092448]]]


In [32]:
# Sí ya que c=b.T, por lo cada entrada de a sólo se multiplicó por 1

In [33]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [34]:
d_max = d.max()
print(d_max)

d_min = d.min()
print(d_min)

d_mean = d.mean()
print(d_mean)


1.9724412647291292
1.0147044677216401
1.5094286147868374


In [35]:
#15. Now we want to label the values in d. First create an empty array 
# "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [36]:
f = np.empty((2,3,5))

In [37]:
print(f)

[[[0.84932765 0.37982056 0.2816592  0.85704966 0.76864715]
  [0.08277764 0.63036587 0.74416352 0.28660003 0.58585179]
  [0.07391217 0.01470447 0.82287469 0.20937815 0.51117295]]

 [[0.97244126 0.54927618 0.19375934 0.50618892 0.62288682]
  [0.95800711 0.47398626 0.28026456 0.63822721 0.82986077]
  [0.12157753 0.34594412 0.57602973 0.48517866 0.63092448]]]


In [38]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

"\n#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.\nIf a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.\nIf a value equals to d_mean, assign 50 to the corresponding value in f.\nAssign 0 to the corresponding value(s) in f for d_min in d.\nAssign 100 to the corresponding value(s) in f for d_max in d.\nIn the end, f should have only the following values: 0, 25, 50, 75, and 100.\nNote: you don't have to use Numpy in this question.\n"

In [39]:

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if (d[i][j][k] > d_min) & (d[i][j][k] < d_mean):
                f[i][j][k]=25
            elif (d[i][j][k] > d_mean) & (d[i][j][k] < d_max):
                f[i][j][k]=75
            elif d[i][j][k] == d_mean:
                f[i][j][k]=50
            elif d[i][j][k]== d_min:
                f[i][j][k]=0
            elif d[i][j][k]==d_max:
                f[i][j][k]=100
                


In [40]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""


'\n#17. Print d and f. Do you have your expected f?\nFor instance, if your d is:\narray([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],\n        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],\n        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],\n\n       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],\n        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],\n        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])\n\nYour f should be:\narray([[[ 75.,  75.,  75.,  25.,  75.],\n        [ 75.,  75.,  25.,  25.,  25.],\n        [ 75.,  25.,  75.,  75.,  75.]],\n\n       [[ 25.,  25.,  25.,  25., 100.],\n        [ 75.,  75.,  75.,  75.,  75.],\n        [ 25.,  75.,   0.,  75.,  75.]]])\n'

In [41]:
print(d)

[[[1.84932765 1.37982056 1.2816592  1.85704966 1.76864715]
  [1.08277764 1.63036587 1.74416352 1.28660003 1.58585179]
  [1.07391217 1.01470447 1.82287469 1.20937815 1.51117295]]

 [[1.97244126 1.54927618 1.19375934 1.50618892 1.62288682]
  [1.95800711 1.47398626 1.28026456 1.63822721 1.82986077]
  [1.12157753 1.34594412 1.57602973 1.48517866 1.63092448]]]


In [42]:
d_max = d.max()
print(d_max)

d_min = d.min()
print(d_min)

d_mean = d.mean()
print(d_mean)

1.9724412647291292
1.0147044677216401
1.5094286147868374


In [43]:
print(f)

[[[ 75.  25.  25.  75.  75.]
  [ 25.  75.  75.  25.  75.]
  [ 25.   0.  75.  25.  75.]]

 [[100.  75.  25.  25.  75.]
  [ 75.  25.  25.  75.  75.]
  [ 25.  25.  75.  25.  75.]]]


In [44]:
"""18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])"""

'18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values \n("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:\narray([[[ \'D\',  \'D\',  \'D\',  \'B\',  \'D\'],\n        [ \'D\',  \'D\',  \'B\',  \'B\',  \'B\'],\n        [ \'D\',  \'B\',  \'D\',  \'D\',  \'D\']],\n\n       [[ \'B\',  \'B\',  \'B\',  \'B\',  \'E\'],\n        [ \'D\',  \'D\',  \'D\',  \'D\',  \'D\'],\n        [ \'B\',  \'D\',   \'A\',  \'D\', \'D\']]])'

In [47]:
f = np.empty((2,3,5), dtype=str)

In [48]:
i=0
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if (d[i][j][k] > d_min) & (d[i][j][k] < d_mean):
                f[i][j][k]='B'
            elif (d[i][j][k] > d_mean) & (d[i][j][k] < d_max):
                f[i][j][k]='D'
            elif d[i][j][k] == d_mean:
                f[i][j][k]='C'
            elif d[i][j][k]== d_min:
                f[i][j][k]='A'
            elif d[i][j][k]==d_max:
                f[i][j][k]='E'

In [49]:
print(d)

[[[1.84932765 1.37982056 1.2816592  1.85704966 1.76864715]
  [1.08277764 1.63036587 1.74416352 1.28660003 1.58585179]
  [1.07391217 1.01470447 1.82287469 1.20937815 1.51117295]]

 [[1.97244126 1.54927618 1.19375934 1.50618892 1.62288682]
  [1.95800711 1.47398626 1.28026456 1.63822721 1.82986077]
  [1.12157753 1.34594412 1.57602973 1.48517866 1.63092448]]]


In [50]:
d_max = d.max()
print(d_max)

d_min = d.min()
print(d_min)

d_mean = d.mean()
print(d_mean)

1.9724412647291292
1.0147044677216401
1.5094286147868374


In [51]:
print(f)

[[['D' 'B' 'B' 'D' 'D']
  ['B' 'D' 'D' 'B' 'D']
  ['B' 'A' 'D' 'B' 'D']]

 [['E' 'D' 'B' 'B' 'D']
  ['D' 'B' 'B' 'D' 'D']
  ['B' 'B' 'D' 'B' 'D']]]
